### ISSUE TITLE
[APIM-4.0.0] [UI BUG-Developer Portal] Incorrect number of APIs displayed when "display_multiple_versions" is set to "false"

### ISSUE THREAD

**Issue by VinulaUthsara** [wso2/api-manager#1343]
### Description

When the following configuration is set to “true” in the deployment.toml as follows:

**[apim.devportal]
display_multiple_versions = true**

All versions of each API will be displayed in the Developer Portal. The number displayed at the bottom of the page will be displayed correctly.

When the above mentioned configuration is set to “false” only the latest version of APIs will be displayed in the Developer Portal. However, the items per page listed will still be displayed as the total number of APIs and not the number of APIs displayed in the UI.

In the image attached below, you can see that the total number of APIs (including versions is 19) but even when only 10 APIs are being displayed "Items per page" shows as 19.

![Screenshot from 2023-01-27 21-59-45](https://user-images.githubusercontent.com/39290953/215383750-000005f2-fe47-4ce0-af89-a6749d4a9aa9.png)

### Steps to Reproduce

1. Add the following configuration to the deployment.toml file with display_multiple_versions = false as follows :

**[apim.devportal]
display_multiple_versions = false**

3. Create an API(s)
4. Create a new version
5. "Items per page" will show the total number of APIs including versions (expected behavior is to show only number of APIs and versions displayed in the developer portal)

### Affected Component

APIM

### Version

4.0.0

**Comment by IsuruMaduranga** [comment]
Hi @VinulaUthsara,

This issue should be already fixed here https://github.com/wso2/product-apim/issues/11627 via https://github.com/wso2/carbon-apimgt/pull/10786. Can you please get the latest APIM pack and confirm whether ths issue is reproducible or not?

Thanks,
Isuru

**Comment by VinulaUthsara** [comment]
Hi @IsuruMaduranga,

The issue is still reproducing in the latest U2 update (178).

Please see attached image:

![Screenshot from 2023-01-31 16-06-03](https://user-images.githubusercontent.com/39290953/215737348-d4f70235-c2f4-4730-8082-4dff534d4bf4.png)

**Comment by IsuruMaduranga** [comment]
Hi @VinulaUthsara,

Closing the issue as the issue can not be reproduced.

Thanks,
Isuru

**Comment by iloshinik** [comment]
Hi @IsuruMaduranga,

Re-opening the issue since the fix for APIM 4.0.0 is yet to be released.

Thanks,
Iloshini

**Comment by IsuruMaduranga** [comment]
Hi @iloshinik,

Fix is released. Closing the issue.

Thanks,
Isuru
