### ISSUE TITLE
Enable editing the issuer from the admin portal for the resident key manager and fixing the null checker

### ISSUE THREAD

**Issue by cbabey** [wso2/api-manager#2392]
### Description

Hi Team,

Once we updated the issuer from the resident Identity provider through the carbon management portal. the same will not be reflected in the gateway server in memory and there is no option in the admin portal to update the issuer configuration. therefore, it is required to enable editing the issuer from the admin portal for the resident key manager.

Thanks and Regards,
Chandima

### Steps to Reproduce

1. Go to the admin server and resident key manager configuration.
2. Just click on the update button without modifying anything in the resident key manager form.
3. After performing the above action, the CONFIGURATION blob in the AM_KEY_MANAGER table gets updated with all the key manager properties, including issuer and enable_token_encryption properties.
4. Updated the issuer claim by modifying the Identity Provider Entity ID value under the Inbound Resident Key Manager -> Authentication Configuration -> OAuth2/OpenID Connect Configuration.
5. Restart the server and invoke the API with the newly generated API.

### Affected Component

APIM

### Version

4.0.0

**Comment by chamilaadhi** [comment]
This issue is already fixed in the public master branch

**Comment by dumindu-nagasinghe** [comment]
Hi all,

This issue persists in API Manager 4.2.0 as well there for opening this issue.

Thanks,
Dumindu

**Comment by SavinduDimal** [comment]
Closing this issue since this is not reproducible in the master branch.
