### ISSUE TITLE
Missing icons in monaco editor in tenant-conf

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/api-manager#2716]
### Description

The icons are missing in the search bar

![Screenshot 2024-03-26 at 16 22 47](https://github.com/wso2/api-manager/assets/25485273/4b26a8fd-a7c5-49f3-9583-93367ecbc162)

### Steps to Reproduce

Go to the Advanced section in admin portal and search something inside the editor

### Affected Component

APIM

### Version

4.3.0

**Comment by chamilaadhi** [comment]
Issue exists in APIM 4.5.0 as well

**Comment by RakinduM** [comment]
Hi, I would like to work on this issue for the Hacktoberfest. Could you assign me for it ? Thanks!

**Comment by chamilaadhi** [comment]
@RakinduM you can start working on this issue

**Comment by RakinduM** [comment]
@chamilaadhi Thanks for assigning me and will get started working on it

**Comment by tharikaGitHub** [comment]
Hi @RakinduM how is the progress of this issue?

**Comment by RakinduM** [comment]
Hi @tharikaGitHub, I'm working on it

**Comment by pavinduLakshan** [comment]
Hi @RakinduM, appreciate it if you can share a progress update or a draft PR so that the maintainers are able to give you early feedback.

**Comment by RakinduM** [comment]
Hi @pavinduLakshan, sure I'll draft the PR asap. It got a little delayed from my end.

**Comment by RakinduM** [comment]
@pavinduLakshan, I guess that issue has been resolved, All the icons in the editor are displaying properly. Could you please let me know if there’s anything else I should do from my end?

<img width="1470" height="832" alt="Image" src="https://github.com/user-attachments/assets/fbb1a942-8eca-4fa3-aad0-525be152bab4" />

**Comment by pavinduLakshan** [comment]
> [@pavinduLakshan](https://github.com/pavinduLakshan), I guess that issue has been resolved, All the icons in the editor are displaying properly. Could you please let me know if there’s anything else I should do from my end?
> 
> <img alt="Image" width="1470" height="832" src="https://private-user-images.githubusercontent.com/116582517/502832154-fbb1a942-8eca-4fa3-aad0-525be152bab4.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjA3ODY3NTksIm5iZiI6MTc2MDc4NjQ1OSwicGF0aCI6Ii8xMTY1ODI1MTcvNTAyODMyMTU0LWZiYjFhOTQyLThlY2EtNGZhMy1hYWQwLTUyNWJlMTUyYmFiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAxOFQxMTIwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDFjYjJjOTI4MmUwODI1MGI1MDNiODEyNjdlOTljZmQwZDg2ZjRkZmI3MDhjMTMxY2RkNmY5M2NjODdmYTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Kqzvfe8XBNNIGWs_XPufmV3U11lTElXqOHt169hFs-M">

Adding the maintainers to the convo cc: @tharikaGitHub @chamilaadhi

**Comment by tharikaGitHub** [comment]
Hi @RakinduM this is still reproducible for me in the latest built pack. Which version of APIM are you checking? Is it APIM 4.5.0? Shall we check with the latest built pack as well? And also what is the browser you are using? The behaviour is the same for Chrome, Safari and Firefox as well.

**Comment by RakinduM** [comment]
Hi @tharikaGitHub, Yeah I have checked it with APIM 4.5.0 and Chrome and Safari as browsers. I'll check it with latest build and fix it.

**Comment by RakinduM** [comment]
Hi @tharikaGitHub & @pavinduLakshan, I have submitted a pull request. Kindly review it and let me know what need to be changed further.

Thank you

**Comment by tharikaGitHub** [comment]
Hi @RakinduM Thank you for your contribution! We will check and get back if anything needs to be changed.

**Comment by RakinduM** [comment]
Thank you @tharikaGitHub ! Sure, let me know if any updates or changes are required.

**Comment by tharikaGitHub** [comment]
Hi @RakinduM, I added some comments to your PR. Apart from that, the other changes are fine. Will you be able to take a look and fix them?

**Comment by RakinduM** [comment]
Yeah sure, I'll fix it

**Comment by tharikaGitHub** [comment]
Hi @RakinduM your PR is approved and accepted for hacktoberfest. Thank you for your contribution! We are currently in a code freeze period due to an on going product release. Therefore we will get your PR merged soon when possible.

**Comment by RakinduM** [comment]
Hi @tharikaGitHub,

Glad to hear that ! I spent some good time with this year Hacktoberfest and really enjoy working on the issues. Thanks for approving the PR and hope to contribute more to WSO2 products.
