### ISSUE TITLE
Operation throttling not working for MCP Servers

### ISSUE THREAD

**Issue by nisan-abeywickrama** [wso2/api-manager#4142]
### Description

Operation throttling policies are not applied to MCP Servers

### Steps to Reproduce

1. Create a throttling policy (eg. 1 request per min)
2. Create an MCP server.
3. Apply the created Policy by enabling operation level throttling.
4. Invoke the MCP Server

### Version

4.6.0-alpha

**Comment by msm1992** [comment]
This issue is fixed in latest 4.6.0 distribition.
Tested with carbon-apimgt version: 9.32.61

**Comment by O-sura** [comment]
This issue is still reproducible in APIM 4.6.0-Alpha2 pack. Hence reopening the issue.

**Comment by msm1992** [comment]
As per confirmations from Osura, throttling applied for MCP but with some addtional number of requests being allowed before being throttled out. This behaviour is described in our official docs, please refer to the note on "Understanding throttling slippage"

[1]. https://apim.docs.wso2.com/en/4.6.0/manage-apis/design/rate-limiting/introducing-throttling-use-cases/#!

**Comment by O-sura** [comment]
This occurs when an MCP server is created using an existing API and in that case, the requests are not throttled at all when operation level is added.

**Comment by msm1992** [comment]
Public fix : https://github.com/wso2/carbon-apimgt/pull/13401/commits/27decefd05f21f792cd3623ac62005396bd613e5

**Comment by Shamly-Shanawaz** [comment]
The issue still persists in Beta 4.6.0, no throttling is applied at operational level. Hence, reopening the issue.
